---
- hosts: _Name_ansible_ubuntu
  become: true 
  tasks:
    - name: create a directory  called court-cases on all  servers
      file:
        path: /home/mike/court-cases
        state: directory 
        mode: 000
        owner: root
        group: root
...
