---
- name: play-app - create tomcat x directories 
  hosts: env_Name_webservers
  become: yes 
  become_user:  root 
  remote_user: ec2-user
  vars:
    ansible_ssh_private_key_file: "/home/devopsmasterjan2023/.ssh/ansible"
  tasks:
    - name: create a username for tomcat 
      user:
        name: john
        group: ec2-user
        shell: /bin/bash 
        home: /home/john

- name: Create directories and users on all staging-webservers
  hosts: stage 
  become: yes   #become grands ansible admin permissions 
  become_user: root 
  tasks:
    - name: create a username for desmond
      user:   #this is the user module
        name: anu
        groups:  mike
        shell: /bin/bash 
        home: /home/anu
    - name: install httpd on all web servers/staging
      yum:     #yum is the package manager for linux system except ubuntu and debian
        name: httpd
        state: installed
