- hosts: env_Name_webservers
  gather_facts: yes 
  remote_user:  ec2-user
  vars:
    ansible_ssh_private_key_file: "/home/devopsmasterjan2023/.ssh/ansible"
    
  tasks:
    - name: Test remote connections on all servers
      ping:
      remote_user: ec2-user     