---
- hosts:  all 
  become:  true 
  tasks:
  -  name: Deploy a user called elvis 
     user: 
       name: elvis    
       create_home:  true
       shell: /bin/bash 
       comment: "elvis is our devops engineer"
       expires:  -1  
       password:  "{{ 'Admin2020' | password_hash('sha512' , 'A512') }}"


         